import ventanas.VentanaPrincipal;


public class Principal {
	
	/*
	 * PRACTICA APLICACION DE GESTION DE ESCRITORIO:
	 * SIGUIENDO LOS CONCEPTOS Y EJEMPLOS MOSTRADOS CREAR UNA APLICACION
	 * DE GESTION DE NEGOCIO, EN LA CUAL, SE GESTIONEN INFORMACIONES SOBRE CLIENTES Y PRODUCTOS
	 * EL PRODUCTO SERA EL DEL NEGOCIO A ELEGIR POR EL PROGRAMADOR
	 * DEBERA TENER AL MENOS 7 CAMPOS, Y DEBERA ESTAR ALMACENADO EN UNA TABLA DE DATOS
	 * 
	 * LA GESTION DEBERA PERMITIR:
	 * REGISTRAR, LISTAR, EDITAR Y BORRAR INFORMACIONES, PERO PARA 
	 * ESTA PARTE SOLO ES NECESARIO REGISTRAR
	 * 
	 * OPCIONALES:
	 * USAR 3 CAMPOS DE ENTRADA NO ENSEÑADOS EN CLASE PARA EL PRODUCTO A ELEGIR
	 * EJ: CHECKBOX, LISTA DESPLEGABLE, RADIO BUTTONS
	 * 
	 * OPC 2:
	 * INTENTAR REALIZAR UN LISTADO DE INFORMACIONES EN LOS PANELES DE LISTADO
	 */

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		new VentanaPrincipal();
	}

}
